OpenModelica/OMTLMSimulator

Hopsan/TLMPluginLib/TLMPluginInterfaceHydraulic1D.hpp, Hopsan/TLMPluginLib/TLMPluginInterfaceSignalOutput.hpp, common/Interfaces/TLMInterface1D.cc, common/Interfaces/TLMInterface1D.h, common/Interfaces/TLMInterface3D.cc, common/Interfaces/TLMInterface3D.h, common/Interfaces/TLMInterfaceSignal.cc, common/Interfaces/TLMInterfaceSignal.h, common/Plugin/PluginImplementer.cc, common/Plugin/PluginImplementer.h, common/Plugin/TLMPlugin.cc, common/Plugin/TLMPlugin.h
Salves can set a start value by calling SetInitialValue(), SetInitialForce1D() or SetInitialForce3D(). It is possible to have different start values on different sides of a connection, since the variables are decoupled.
Tested for signal and 1D connections in Hopsan wrapper. Backwards compatibility is also verified (hence, all models which does not set initial values will still simulate as they used to).
=> Made it possible for submodels to set start values of forces/values.

common/Communication/ManagerCommHandler.cc
Some slaves do not send close requests, so we should not wait forever for them. If a socket is closed, it is closed.
=> Allow closing sockets without permission.

common/Communication/ManagerCommHandler.cc
Counter for closed sockets was inremented too often, so all interfaces did not receive proper start values.
=> Proper shutdown after fetch interfaces

common/Makefile
This suppresses a lot of unnecessary compiler warnings.
=> Add C++11 flag for manager and monitor

common/Logging/TLMErrorLog.cc, common/ManagerMain.cc
Messages printed through cout will show up in OMEdit dialog. This makes it easier for the user to understand why the simulation did not work.
=> Enable warning output. Print errors and warnings to cout.

common/CompositeModels/CompositeModel.cc, common/CompositeModels/CompositeModel.h, common/ManagerMain.cc
Causalities and domains should match.
Interfaces shall not be connected more than once.
Warn user about unconnected interfaces.
=> Check the model for errors prior to simulation.

common/Communication/TLMManagerComm.cc
Simulation always waits for this timeout after successful simulation. Waiting 10 seconds is really annoying for small models.
=> Reduced monitor timeout to avoid delay at end of simulation.

FMIWrapper/main.cpp, common/Communication/ManagerCommHandler.cc, common/Communication/TLMClientComm.cc, common/CompositeModels/CompositeModel.cc, common/Logging/TLMErrorLog.cc, common/Logging/TLMErrorLog.h, common/MonitorMain.cc, common/Plugin/MonitoringPluginImplementer.cc
Especially by avoiding certain function calls when debug logging is disabled. Also made it possible to completely disable data logging from FMIWrapper. These were the main bottlenecks found by valgrind.
=> Various performance improvements

FMIWrapper/Makefile, Hopsan/Makefile
Otherwise make arguments will not propagate.
=> Use MAKE variable instead of make in makefiles

common/Interfaces/TLMInterfaceSignal.cc, common/Plugin/PluginImplementer.cc, common/Plugin/PluginImplementer.h
Instead of each component closing after first output interface, they should close after all interfaces have sent and/or received data.
=> Fetch interface feature should work for multiple connections and sinks

common/Makefile, common/OMTLMSimulatorLib/OMTLMSimulatorLib.h
- fPIC flag should be used on Linux, but not on Windows/MinGW (to avoid warnings).
- declspec(dllexport) should only be used on Windows.
=> Compilation fixes for Linux

common/Communication/ManagerCommHandler.h, common/CompositeModels/CompositeModel.cc, common/CompositeModels/CompositeModel.h, common/CompositeModels/CompositeModelReader.h, common/Logging/TLMErrorLog.cc, common/ManagerMain.cc, common/MonitorMain.cc, common/OMTLMSimulatorLib/OMTLMSimulatorLib.cc
Both OMSimulator and OMTLMSimualtor have classes named "CompositeModel". When dynamically linking OMTLMSimulator to OMSimulator, the class names will collide.
Perhaps a namespace would be better, but this works for now.
=> Renamed CompositeModel to avoid name conflict with OMSimulator.

common/Communication/ManagerCommHandler.cc, common/Communication/ManagerCommHandler.h, common/Communication/TLMCommUtil.cc, common/OMTLMSimulatorLib/OMTLMSimulatorLib.cc, common/Plugin/PluginImplementer.cc, common/Plugin/PluginImplementer.h, common/Plugin/TLMPlugin.h
- Use close request messages also for monitor
- Don't attempt to send data to monitor if it is disconnected
- Resend failed messages 10 times, then abort simulation
- Don't close TLM error log in each thread
- Apply TLM log level at very beginning, to catch early messages
=> Fix monitor shutdown

common/OMTLMSimulatorLib/OMTLMSimulatorLib.cc
When running on kubernetes, etc, you get hostname that will not
resolve. Easy fix is to simply set AF_INET and open the port.
=> Simply checks since only AF_INET is supported

common/Communication/ManagerCommHandler.cc, common/Communication/ManagerCommHandler.h, common/OMTLMSimulatorLib/OMTLMSimulatorLib.cc, common/Plugin/PluginImplementer.cc, common/Plugin/PluginImplementer.h, common/Plugin/TLMPlugin.h
Related to #109 and OpenModelica/OMSimulator#618
- Wait for close persmission before closing monitor socket
- Send close permission to monitor _after_ closing all slave sockets
=> Close connection to monitor after slaves

common/Communication/TLMManagerComm.cc
Remove unnecessary check for AF_INET. Check is not needed, and the check itself may fail on some architectures. Related to #111.
=> Remove AF_INET check in TLM manager

common/CompositeModels/CompositeModel.cc, common/CompositeModels/CompositeModel.h, common/CompositeModels/CompositeModelReader.cc, common/OMTLMSimulatorLib/OMTLMSimulatorLib.cc
- Added option to override socket address
- If not used, socket address from manager will be read from hostname automatically
- OMTLMSimulator library will use this feature by calling `omtlm_setAddress`
=> Option to override socket address

common/CompositeModels/CompositeModel.h, common/OMTLMSimulatorLib/OMTLMSimulatorLib.cc, common/OMTLMSimulatorLib/OMTLMSimulatorLib.h
OMTLMSimulator API for fetching external model interfaces.  
`omtlm_fetchInterfaces` will start a single-step simulation with a single external model. Interface data will be written to interfaceData.xml in the current directory.
Required by OpenModelica/OMSimulator#704.
=> API for fetching submodel interfaces

common/CompositeModels/CompositeModel.cc
The signal handler in OMTLMSimulator seem to conflict with some Git process features in OMEdit. We don't actually need it until we start the processes (the external models), since it only catches SIGCHLD i.e. return codes from child processes. Therefore I moved it to the 'StartComponents` function.
Perhaps this needs a more proper solution later, but this works for the moment at least.
=> Install signal handler just before starting components

common/Communication/TLMThreadSynch.h
Looks like this was intended here? If yes, then this fix silences out a false positive shown in many places during compilation (since it is in a header).
=> Fix compiler warning on unused expression

Makefile.head
https://github.com/OpenModelica/OMSimulator/issues/1024
This PR, fixes the static linking of `libstdc++` on `ming32` bit platforms
=> Link with static libstdc++ for mingw32

common/Communication/TLMClientComm.cc, common/Communication/TLMCommUtil.h, common/Communication/TLMManagerComm.cc, common/OMTLMSimulatorLib/OMTLMSimulatorLib.cc, common/OMTLMSimulatorMain.cc
Also solving some warnings about `NOMINMAX` defined multiple times.
=> Solving compiler error on Windows with setsockopt 
